//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokSatis.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_SATISLAR
    {
        public int SATISID { get; set; }
        public Nullable<int> MUSTERI { get; set; }
        public Nullable<int> URUN { get; set; }
        [Required(ErrorMessage = "Fiyat boþ geçilemez!")]
        public Nullable<decimal> FIYAT { get; set; }
        [Required(ErrorMessage = "Ürün adeti boþ geçilemez!")]
        public Nullable<int> ADET { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> SATICI { get; set; }
    
        public virtual TBL_GIRIS TBL_GIRIS { get; set; }
        public virtual TBL_MUSTERILER TBL_MUSTERILER { get; set; }
        public virtual TBL_URUNLER TBL_URUNLER { get; set; }
    }
}
